import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export const generateBrochure = (university) => {
  const doc = new jsPDF();
  const primaryColor = [13, 148, 136]; // #0d9488 (Teal/Primary)

  // Header Background
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(university.name, 105, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${university.city}, ${university.state}`, 105, 30, { align: 'center' });

  // Body
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text("University Overview", 14, 55);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const details = [
    ["Type", university.type || 'Private'],
    ["NIRF Rank", university.nirfRank || 'N/A'],
    ["NAAC Grade", university.naacGrade || 'N/A'],
    ["Website", university.website || 'N/A'],
    ["Contact", university.email || university.phone || 'N/A']
  ];

  doc.autoTable({
    startY: 60,
    head: [['Parameter', 'Detail']],
    body: details,
    theme: 'striped',
    headStyles: { fillColor: primaryColor }
  });

  // Stats
  let currentY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text("Statistics & Highlights", 14, currentY);

  const stats = [
    ["Average Package", `${university.stats?.avgPackageLPA || '4.5'} LPA`],
    ["Highest Package", `${university.stats?.highestPackageLPA || '12.0'} LPA`],
    ["Campus Size", `${university.stats?.campusSizeAcres || '50'} Acres`],
    ["Hostel Facility", university.campus?.hostelDetails || 'Available'],
    ["Placement Rate", `${university.stats?.placementPercentage || '85'}%`]
  ];

  doc.autoTable({
    startY: currentY + 5,
    body: stats,
    theme: 'plain',
    columnStyles: { 0: { fontStyle: 'bold' } }
  });

  // Courses
  currentY = doc.lastAutoTable.finalY + 15;
  if (university.courses && university.courses.length > 0) {
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text("Programs Offered", 14, currentY);

    const courses = university.courses.map(c => [c.name, c.category, `${c.duration} Years`, c.feesPerYear ? `Rs. ${c.feesPerYear}` : 'Contact University']);
    doc.autoTable({
      startY: currentY + 5,
      head: [['Course Name', 'Level', 'Duration', 'Fees (Annual)']],
      body: courses,
      headStyles: { fillColor: primaryColor }
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by Vidyarthi Mitra - Find Your Perfect University`, 105, 285, { align: 'center' });
    doc.text(`Page ${i} of ${pageCount}`, 190, 285, { align: 'right' });
  }

  doc.save(`${university.slug}_brochure.pdf`);
};
